export type IndustryCategory =
  | "Creative"
  | "Engineering"
  | "Business"
  | "Science"
  | "Social Impact";

export type Industry = {
  slug: string;
  name: string;
  category: IndustryCategory;
  shortBlurb: string;
  whatYouDo: string;
  beginnerFriendly: boolean;
  featuredDemo: boolean;
  demoRoute?: string;
  tags: string[];
  icon?: string;
};

export const INDUSTRIES: Industry[] = [
  {
    slug: "music-production",
    name: "Music Production",
    category: "Creative",
    shortBlurb: "Build beats, shape emotion, and learn the tools behind the songs you love.",
    whatYouDo: "You design rhythm, texture, and arrangement, then polish the sound with effects and mixing.",
    beginnerFriendly: true,
    featuredDemo: true,
    demoRoute: "/labs/music",
    tags: ["beats", "DAW", "rhythm", "effects", "mixing"],
    icon: "Music2",
  },
  {
    slug: "automotive-engineering",
    name: "Automotive Engineering",
    category: "Engineering",
    shortBlurb: "Turn performance trade-offs into real decisions: speed, control, and reliability.",
    whatYouDo: "You design and test vehicles, using data to improve safety, efficiency, and performance.",
    beginnerFriendly: true,
    featuredDemo: true,
    demoRoute: "/labs/pitstop",
    tags: ["mechanics", "systems", "telemetry", "strategy", "motorsport"],
    icon: "Wrench",
  },
  {
    slug: "investment-banking",
    name: "Investment Banking",
    category: "Business",
    shortBlurb: "Learn how deals are structured and how negotiation shapes outcomes.",
    whatYouDo: "You advise companies on big decisions like fundraising, mergers, and going public.",
    beginnerFriendly: false,
    featuredDemo: true,
    demoRoute: "/labs/dealroom",
    tags: ["deals", "valuation", "negotiation", "strategy", "markets"],
    icon: "Landmark",
  },

  // Creative
  {
    slug: "film-editing",
    name: "Film Editing",
    category: "Creative",
    shortBlurb: "Make stories feel fast, slow, funny, or intense by cutting with purpose.",
    whatYouDo: "You shape pacing and emotion by choosing shots, timing, sound, and transitions.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["story", "pacing", "sound", "timeline"],
    icon: "Film",
  },
  {
    slug: "game-design",
    name: "Game Design",
    category: "Creative",
    shortBlurb: "Design rules, challenges, and moments that keep players curious.",
    whatYouDo: "You create systems and levels, then test and refine how it feels to play.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["levels", "systems", "playtesting", "creativity"],
    icon: "Gamepad2",
  },
  {
    slug: "graphic-design",
    name: "Graphic Design",
    category: "Creative",
    shortBlurb: "Make ideas clear and beautiful through typography, layout, and color.",
    whatYouDo: "You design visuals for brands, posters, apps, and social media.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["typography", "layout", "branding", "color"],
    icon: "Palette",
  },
  {
    slug: "fashion-technology",
    name: "Fashion Technology",
    category: "Creative",
    shortBlurb: "Blend design + engineering: smart textiles, wearable prototypes, and new materials.",
    whatYouDo: "You prototype clothing with sensors, new fabrics, and performance constraints.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["wearables", "materials", "prototyping", "design"],
    icon: "Shirt",
  },

  // Engineering
  {
    slug: "robotics",
    name: "Robotics",
    category: "Engineering",
    shortBlurb: "Build machines that sense, move, and help people in the real world.",
    whatYouDo: "You combine mechanics, electronics, and code to create autonomous systems.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["mechanical", "electronics", "control", "autonomy"],
    icon: "Bot",
  },
  {
    slug: "aerospace-engineering",
    name: "Aerospace Engineering",
    category: "Engineering",
    shortBlurb: "Design aircraft and spacecraft where safety and physics are everything.",
    whatYouDo: "You test structures, propulsion, and guidance to make flight possible.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["flight", "structures", "propulsion", "simulation"],
    icon: "Rocket",
  },
  {
    slug: "architecture",
    name: "Architecture",
    category: "Engineering",
    shortBlurb: "Design spaces that are functional, safe, and inspiring to live in.",
    whatYouDo: "You plan buildings, iterate on models, and balance constraints like cost and climate.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["design", "structures", "models", "sustainability"],
    icon: "Building2",
  },
  {
    slug: "cybersecurity",
    name: "Cybersecurity",
    category: "Engineering",
    shortBlurb: "Protect people and systems by thinking like a defender and an attacker.",
    whatYouDo: "You find vulnerabilities, harden systems, and respond to incidents.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["privacy", "defense", "networks", "risk"],
    icon: "Shield",
  },
  {
    slug: "renewable-energy",
    name: "Renewable Energy",
    category: "Engineering",
    shortBlurb: "Build cleaner power systems and make energy more accessible.",
    whatYouDo: "You design solar, wind, and storage systems and optimize efficiency.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["climate", "systems", "grid", "efficiency"],
    icon: "Leaf",
  },

  // Business
  {
    slug: "product-management",
    name: "Product Management",
    category: "Business",
    shortBlurb: "Turn messy problems into clear plans and shipped features.",
    whatYouDo: "You align teams, define requirements, and decide what matters most.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["strategy", "communication", "roadmap", "users"],
    icon: "Target",
  },
  {
    slug: "entrepreneurship",
    name: "Entrepreneurship",
    category: "Business",
    shortBlurb: "Start something from scratch and learn fast through real feedback.",
    whatYouDo: "You validate ideas, build a team, and iterate toward product-market fit.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["startup", "experiments", "pitch", "growth"],
    icon: "Lightbulb",
  },
  {
    slug: "marketing",
    name: "Marketing",
    category: "Business",
    shortBlurb: "Help people discover products by telling a story that fits them.",
    whatYouDo: "You run campaigns, test messages, and measure what works.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["storytelling", "analytics", "brand", "campaigns"],
    icon: "Megaphone",
  },
  {
    slug: "ux-research",
    name: "UX Research",
    category: "Business",
    shortBlurb: "Understand people’s needs so products feel intuitive and fair.",
    whatYouDo: "You run interviews, usability tests, and synthesize insights.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["users", "research", "empathy", "testing"],
    icon: "Search",
  },
  {
    slug: "operations",
    name: "Operations",
    category: "Business",
    shortBlurb: "Make organizations run smoothly, efficiently, and sustainably.",
    whatYouDo: "You design processes and fix bottlenecks across teams.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["systems", "process", "efficiency", "planning"],
    icon: "Workflow",
  },

  // Science
  {
    slug: "biology",
    name: "Biology",
    category: "Science",
    shortBlurb: "Study life from cells to ecosystems, then use it to solve problems.",
    whatYouDo: "You run experiments, analyze results, and build explanations.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["lab", "experiments", "health", "nature"],
    icon: "Dna",
  },
  {
    slug: "neuroscience",
    name: "Neuroscience",
    category: "Science",
    shortBlurb: "Explore how brains learn, remember, and change over time.",
    whatYouDo: "You study neurons, behavior, and brain systems using experiments and data.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["brain", "learning", "research", "data"],
    icon: "Brain",
  },
  {
    slug: "climate-science",
    name: "Climate Science",
    category: "Science",
    shortBlurb: "Measure change, model the future, and communicate what matters.",
    whatYouDo: "You analyze climate data and help communities prepare.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["climate", "models", "data", "impact"],
    icon: "CloudSun",
  },
  {
    slug: "chemistry",
    name: "Chemistry",
    category: "Science",
    shortBlurb: "Understand what materials are made of and how they react.",
    whatYouDo: "You test mixtures, build compounds, and model reactions.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["materials", "lab", "reactions", "safety"],
    icon: "FlaskConical",
  },
  {
    slug: "data-science",
    name: "Data Science",
    category: "Science",
    shortBlurb: "Turn raw data into clear decisions and useful predictions.",
    whatYouDo: "You clean data, build models, and explain results.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["analysis", "models", "stats", "visualization"],
    icon: "BarChart3",
  },

  // Social Impact
  {
    slug: "public-policy",
    name: "Public Policy",
    category: "Social Impact",
    shortBlurb: "Design rules and programs that improve real people’s lives.",
    whatYouDo: "You research, write proposals, and evaluate what’s working.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["community", "law", "research", "systems"],
    icon: "Scale",
  },
  {
    slug: "education-technology",
    name: "Education Technology",
    category: "Social Impact",
    shortBlurb: "Build tools that make learning more accessible and engaging.",
    whatYouDo: "You design experiences that support students and teachers.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["learning", "accessibility", "design", "students"],
    icon: "GraduationCap",
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    category: "Social Impact",
    shortBlurb: "Support health through care, communication, and evidence-based practice.",
    whatYouDo: "You help patients, coordinate care, and improve outcomes.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["care", "science", "community", "support"],
    icon: "HeartPulse",
  },
  {
    slug: "mental-health-advocacy",
    name: "Mental Health Advocacy",
    category: "Social Impact",
    shortBlurb: "Reduce stigma and make support more reachable and normal.",
    whatYouDo: "You build programs, resources, and peer support systems.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["support", "community", "wellbeing", "access"],
    icon: "HandHeart",
  },
  {
    slug: "environmental-justice",
    name: "Environmental Justice",
    category: "Social Impact",
    shortBlurb: "Make sure climate solutions are fair, local, and people-first.",
    whatYouDo: "You work with communities to address pollution and access to clean resources.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["climate", "equity", "community", "policy"],
    icon: "Sprout",
  },

  // Extra breadth (to reach 30+)
  {
    slug: "sports-analytics",
    name: "Sports Analytics",
    category: "Science",
    shortBlurb: "Use data to understand performance and strategy in games.",
    whatYouDo: "You track metrics, build models, and explain decisions to teams.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["data", "strategy", "performance"],
    icon: "Activity",
  },
  {
    slug: "journalism",
    name: "Journalism",
    category: "Social Impact",
    shortBlurb: "Ask good questions, verify facts, and tell stories that matter.",
    whatYouDo: "You interview, investigate, and communicate clearly to the public.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["writing", "research", "storytelling"],
    icon: "Newspaper",
  },
  {
    slug: "law",
    name: "Law",
    category: "Business",
    shortBlurb: "Use logic, evidence, and advocacy to protect people and resolve disputes.",
    whatYouDo: "You research cases, write arguments, and negotiate outcomes.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["advocacy", "writing", "logic"],
    icon: "Gavel",
  },
  {
    slug: "ai-research",
    name: "AI Research",
    category: "Science",
    shortBlurb: "Explore how machines learn and how to make them safer and more useful.",
    whatYouDo: "You run experiments, read papers, and build prototypes to test ideas.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["ml", "research", "ethics", "models"],
    icon: "Cpu",
  },
  {
    slug: "community-organizing",
    name: "Community Organizing",
    category: "Social Impact",
    shortBlurb: "Bring people together to create change through local action.",
    whatYouDo: "You listen, plan events, and build momentum around goals.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["community", "leadership", "impact"],
    icon: "Users",
  },
  {
    slug: "photography",
    name: "Photography",
    category: "Creative",
    shortBlurb: "Capture stories with light, framing, and timing.",
    whatYouDo: "You shoot, edit, and build a style that communicates a point of view.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["composition", "editing", "visuals"],
    icon: "Camera",
  },
  {
    slug: "civil-engineering",
    name: "Civil Engineering",
    category: "Engineering",
    shortBlurb: "Design bridges, roads, and infrastructure that people rely on every day.",
    whatYouDo: "You model loads, choose materials, and plan safe construction.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["structures", "infrastructure", "safety"],
    icon: "Route",
  },
  {
    slug: "biomedical-engineering",
    name: "Biomedical Engineering",
    category: "Engineering",
    shortBlurb: "Build medical devices that improve and save lives.",
    whatYouDo: "You prototype devices, test safety, and work with clinicians.",
    beginnerFriendly: false,
    featuredDemo: false,
    tags: ["health", "devices", "design", "testing"],
    icon: "Stethoscope",
  },
  {
    slug: "supply-chain",
    name: "Supply Chain",
    category: "Business",
    shortBlurb: "Move products from idea to shelf without chaos.",
    whatYouDo: "You forecast demand, coordinate suppliers, and manage constraints.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["planning", "logistics", "systems"],
    icon: "Truck",
  },
  {
    slug: "astronomy",
    name: "Astronomy",
    category: "Science",
    shortBlurb: "Study stars, galaxies, and the physics of the universe.",
    whatYouDo: "You analyze telescope data and build models of cosmic behavior.",
    beginnerFriendly: true,
    featuredDemo: false,
    tags: ["space", "data", "physics"],
    icon: "Telescope",
  },
];

export const FEATURED_INDUSTRIES = INDUSTRIES.filter((industry) => industry.featuredDemo);

